export const EDIT_GAME_REQUEST = 'EDIT_GAME_REQUEST'
export const EDIT_GAME_SUCCESS = 'EDIT_GAME_SUCCESS'
export const EDIT_GAME_FAILURE = 'EDIT_GAME_FAILURE'
export const FORM_INPUT_CHANGE = 'FORM_INPUT_CHANGE'