export const FETCH_ONPLAY_GAMES_REQUEST = 'FETCH_ONPLAY_GAMES_REQUEST'
export const FETCH_ONPLAY_GAMES_SUCCESS = 'FETCH_ONPLAY_GAMES_SUCCESS'
export const FETCH_ONPLAY_GAMES_FAILURE = 'FETCH_ONPLAY_GAMES_FAILURE'